
package br.com.caelum.estoque.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EstoqueWS", targetNamespace = "http://ws.estoque.caelum.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EstoqueWS {


    /**
     * 
     * @param codigo
     * @return
     *     returns java.util.List<br.com.caelum.estoque.soap.ItemEstoque>
     */
    @WebMethod(operationName = "ItensPeloCodigo")
    @WebResult(name = "ItemEstoque", targetNamespace = "")
    @RequestWrapper(localName = "ItensPeloCodigo", targetNamespace = "http://ws.estoque.caelum.com.br/", className = "br.com.caelum.estoque.soap.ItensPeloCodigo")
    @ResponseWrapper(localName = "ItensPeloCodigoResponse", targetNamespace = "http://ws.estoque.caelum.com.br/", className = "br.com.caelum.estoque.soap.ItensPeloCodigoResponse")
    public List<ItemEstoque> itensPeloCodigo(
        @WebParam(name = "codigo", targetNamespace = "")
        List<String> codigo);

}
